# Generated by Django 6.0.4 on 2026-04-20 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('socket', models.CharField(max_length=50)),
                ('form_factor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cores', models.IntegerField()),
                ('frequency', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('memory', models.IntegerField()),
                ('chipset', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ComputerBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('motherboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc_builder.motherboard')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc_builder.processor')),
                ('videocard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc_builder.videocard')),
            ],
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc_builder.computerbuild')),
            ],
        ),
    ]
