# Generated by Django 6.0.4 on 2026-04-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processor',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='processors', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='videocard',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='videocards', verbose_name='Изображение'),
        ),
    ]
